version: "2"
services:
  web:
    container_name: tailwind-testing.apache
    image: gravatalonga/docker-apache2laravel:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
    links:
      - php

  php:
    container_name: tailwind-testing.php
    image: gravatalonga/docker-php7.0:latest
    ports:
      - "9001:9001"
      - "22:22"
    volumes:
      - ./:/var/www
    links:
      - db
      - redis
      - mailhog

  db:
    container_name: tailwind-testing.maria
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./.database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=control

  redis:
    container_name: tailwind-testing.redis
    image: redis
    ports:
      - "6379:6379"

  mailhog:
    container_name: tailwind-testing.mailhog
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"