version: "2"
services:
  web:
    container_name: tailwind-testing.apache
    image: gravatalonga/docker-apache2laravel:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
    links:
      - php

  php:
    container_name: tailwind-testing.php
    image: gravatalonga/docker-php7.0:latest
    ports:
      - "9001:9001"
      - "22:22"
    volumes:
      - ./:/var/www